export const background = require('./assets/background/background.png')
export const logo = require('./assets/background/logo.png')
export const notified = require('./assets/background/notified.png')
export const topDesign = require('./assets/background/topDesign.png')
export const N = require('./assets/novelish/N.png')
export const O = require('./assets/novelish/O.png')
export const V = require('./assets/novelish/V.png')
export const E = require('./assets/novelish/E.png')
export const L = require('./assets/novelish/L.png')
export const I = require('./assets/novelish/I.png')
export const S = require('./assets/novelish/S.png')
export const T = require('./assets/novelish/T.png')

export const gradient = require('./assets/novelish/gradient.png')
